name: CI-CD to AKS (Azure)

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: devops-python-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump Version and Create Tag
        id: bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch   # increments patch version (v1.0.0 â†’ v1.0.1)
          WITH_V: true          # ensures tags are prefixed with 'v'

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          az acr login --name $(echo ${{ secrets.ACR_LOGIN_SERVER }} | cut -d'.' -f1)

      - name: Build & Push Image (Auto Version)
        run: |
          VERSION=${{ steps.bump.outputs.new_tag }}
          echo "Building image with version: $VERSION"

          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:$VERSION .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:$VERSION

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AKS_RG }} \
            --name ${{ secrets.AKS_NAME }} \
            --overwrite-existing

      - name: Deploy to AKS
        run: |
          VERSION=${{ steps.bump.outputs.new_tag }}
          kubectl set image deployment/devops-python-app \
            app=${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:$VERSION \
            -n app

          kubectl rollout status deployment/devops-python-app -n app --timeout=120s

